backend:
  name: git-gateway
  branch: aphantasia
editor:
  preview: false
media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }

      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Prompt, name: prompt, widget: text}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}

      - file: "site/content/parents/_index.md"
        label: "Information for Parents"
        name: "parents"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Section Title, name: title, widget: string}
              - {label: Section Text, name: text, widget: markdown}
              - label: Items (optional)
                name: items
                widget: list
                required: false
                fields:
                  - {label: Item Title, name: title, widget: string}
                  - {label: Item Text, name: text, widget: markdown}
          - {label: Bottom Text, name: bottom_text, widget: markdown, required: false}

      - file: "site/content/teachers/_index.md"
        label: "Information for Teachers"
        name: "teachers"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Section Title, name: title, widget: string}
              - {label: Section Text, name: text, widget: markdown}

      - file: "site/content/tests/_index.md"
        label: "Join Research / Tests"
        name: "tests"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Survey Link, name: survey_link, widget: string}
          - {label: Tests Title, name: tests_title, widget: string}
          - {label: Tests Description, name: tests_description, widget: markdown}
          - label: Test List
            name: test_list
            widget: list
            fields:
              - {label: Test Title, name: title, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Link, name: link, widget: string}
              - {label: Citation, name: citation, widget: text}

      - file: "site/content/researchers/_index.md"
        label: "Resources for Researchers"
        name: "researchers"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Top Sections
            name: top_sections
            widget: list
            fields:
              - {label: Section Title, name: title, widget: string}
              - {label: Section Text, name: text, widget: markdown}
          - label: Bibliography
            name: bibliography
            widget: list
            fields:
              - {label: Section Title, name: section_title, widget: string}
              - label: Citations
                name: citations
                widget: list
                fields:
                  - {label: Citation, name: citation, widget: text}
                  - {label: Link, name: link, widget: string, required: false}
          - label: Bottom Sections
            name: bottom_sections
            widget: list
            fields:
              - {label: Section Title, name: title, widget: string}
              - {label: Section Text, name: text, widget: markdown}

      - file: "site/content/faq/_index.md"
        label: "FAQ Page"
        name: "faq"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Question, name: title, widget: string}
              - {label: Answer, name: text, widget: markdown}

      - file: "site/content/about/_index.md"
        label: "About"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: string, required: false}
          - {label: Intro, name: intro, widget: string}
          - {label: "Team Title", name: team_title, widget: string}
          - label: "Team Members"
            name: team_members
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Bio, name: bio, widget: string}
          - {label: "Previous Team Members section header", name: previous_members_header, widget: string}
          - label: 'Previous Team Members'
            name: previous_team_members
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Bio, name: bio, widget: string}

      - file: "site/hugo.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: {label: Image, name: image, widget: image}
